### ISSUE TITLE
PyTorch Lightning EcoCI integration to check for compatibility with latest & upcoming releases

### ISSUE THREAD

**Issue by rasbt** [grok-ai/nn-template#73]
Hey Valentino & Luca, 

I am just catching up with some bookmarks and remembered your repo here :). As someone who constantly fuzzes about the ideal project structure, that's actually pretty cool. I have been using an adapted version of the data science cookiecutter for generic ML projects, but nothing sophisticated like this here with code stubs. 

Haven't thoroughly played with it yet, though, besides creating an example folder and looking at the `pl_module.py` and `datamodule.py` files, which look good to me! 

In any case, long story short, I was wondering if you'd be interested in the PyTorch Lightning's ecosystem CI to make sure that it stays fresh and relevant wrt to upcoming version releases (comes with free CPU and multi-GPU CI tests): https://devblog.pytorchlightning.ai/stay-ahead-of-breaking-changes-with-the-new-lightning-ecosystem-ci-b7e1cf78a6c7

If you are interested in that, I am sure my colleague @Borda would be happy to assist with questions & technical details -- he built this thing, so he probably knows best :)

**Comment by lucmos** [comment]
Hello Sebastian,

Thank you for your message!
We are definitely interested in Lightning's ecosystem CI.  Actually, I did already read something about it and thought our template would be a perfect use case for it.

Unfortunately at the moment, we do not have a lot of bandwidth to work on it and we are not sure of the amount of work required to set it up.

**Comment by Borda** [comment]
> Unfortunately at the moment, we do not have a lot of bandwidth to work on it and we are not sure of the amount of work required to set it up.

Hello, I think we are happy to help! I may suggest if you can open a PR which just draft receipt and we can then finish it for you... How does it sound? :rabbit:

**Comment by lucmos** [comment]
Thank you so much for your interest and offer!

I opened a Draft PR https://github.com/PyTorchLightning/ecosystem-ci/pull/44, I also tried to highlight what I found difficult to configure :smiley:

**Comment by lucmos** [comment]
I think we can continue the discussion in https://github.com/Lightning-AI/ecosystem-ci/pull/44

Thanks! :smile:
