### ISSUE TITLE
load_model

### ISSUE THREAD

**Issue by framolfese** [grok-ai/nn-template#81]
Hi,
This issue concerns the function **from nn_core.serialization import load_model**
Suppose i train a pytorch model with class **MyLightningModule**, and that I saved the checkpoint in **model_path**. 
Suppose now that the class MyLightningModule has received some minor changes, like a new class variable has been added. 
Let's call this version **MyLightningModuleV2**.
When I load a model using this function, like:

`self.model = load_model(module_class=MyLightningModuleOld, checkpoint_path=Path(model_path), map_location=self.device).to(self.device).eval()`

I get an error because the chekpoint refers to the model of class MyLightningModule and therefore the new variable is (obviously) missing. 
To make it work, i need to load the model with the old version of the class, that is, MyLightningModule, and then manually setting "model.new_variable" to the value i want to get, like the following:
```
self.model = load_model(module_class=MyLightningModuleOld, checkpoint_path=Path(model_path), map_location=self.device).to(self.device).eval()
self.model.new_variable = False
```
It would be nice to have this option in the load_model function to avoid creating multiple versions of the same class.

**Comment by lucmos** [comment]
Hello,

That is the standard behaviour in torch and most similar libraries that I am aware of: they do not package the code in the checkpoint but rely on in being available at runtime.

Recently we improved the situation a little bit allowing non `strict` loading with a parameter, but I do not think this is a feature that we can tackle at the template level (neither it is clear how to implement it nicely).

Thus I am closing this issue -- feel free to re-open it if there are some ways to implement it nicely in a generic way that I am not aware of. Note that the problem does not involve only the code but also the environment itself (in theory, if you 
 want a checkpoint to be self-contained it should contain also all the required dependencies) :smile:
