### ISSUE TITLE
Update LightningDataModule example usage

### ISSUE THREAD

**Issue by LeonardoEmili** [grok-ai/nn-template#94]
I believe [L217](https://github.com/grok-ai/nn-template/blob/8471d9a36c2e73356196e30fd58bcedac43613fe/%7B%7B%20cookiecutter.repository_name%20%7D%7D/src/%7B%7B%20cookiecutter.package_name%20%7D%7D/data/datamodule.py#L217C14-L217C14) in `datamodule.py` should be changed from
```
_: pl.LightningDataModule = hydra.utils.instantiate(cfg.data.datamodule, _recursive_=False)
```
to
```
_: pl.LightningDataModule = hydra.utils.instantiate(cfg.nn.data, _recursive_=False)
```

Thanks for the great project, keep up with the good work! @lucmos

**Comment by lucmos** [comment]
Thank you! Yes, good catch! 😁
Would you mind opening a PR with the fix?
